# Generated by Django 3.2.8 on 2021-10-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acc_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('account_num', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('mob_no', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
